"""Where the training data comes from — and what that costs.

Every example is generated by :mod:`glpi_testkit`. **No client ticket is
involved at any point**, which is what makes the model publishable at all.

That choice has a price, and it has to be stated plainly rather than buried:

> The tickets are built from templates. A model trained on them partly learns
> the templates. Accuracy measured on held-out synthetic data is therefore an
> **upper bound on the pipeline**, not a prediction of accuracy on a real
> service desk.

What the numbers do establish: that the pipeline trains, that it generalises
across three languages rather than latching onto one, and that it beats the
trivial baselines by a wide margin. To get a figure that means something on
real tickets you have to fine-tune on real tickets — which is exactly the
scoping engagement this demo is meant to start, not replace.

**Measured template saturation.** The generator draws from a finite set of
templates, so unique texts do not grow with the sample size:

===============  ==============  ==========
tickets drawn    unique texts    diversity
===============  ==============  ==========
500              289             58%
2000             771             39%
8000             1871            23%
20000            3068            15%
===============  ==============  ==========

Consequence: drawing train and test from different seeds is **not** enough to
separate them. Measured at train=6000 / test=2000, **24% of test texts appeared
verbatim in training**. :func:`train_test_split` therefore deduplicates by
default, dropping any test row whose text occurs in the training half.

Even deduplicated, a test text is a *template sibling* of a training text — same
sentence pattern, different slot values. So the split measures generalisation
across slot values, not across writing styles. It is the strongest measurement
this data supports, and still not a prediction about real tickets.

The generator is seeded, so the same seed always produces the same split.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from glpi_testkit import Language, TicketGenerator


@dataclass(frozen=True, slots=True)
class Dataset:
    """Texts and their labels, with the language kept for per-language scoring."""

    texts: list[str]
    categories: list[str]
    priorities: list[int]
    languages: list[str]

    def __len__(self) -> int:
        return len(self.texts)

    def subset(self, language: str) -> Dataset:
        """The rows written in one language."""
        keep = [
            index for index, value in enumerate(self.languages) if value == language
        ]
        return Dataset(
            texts=[self.texts[i] for i in keep],
            categories=[self.categories[i] for i in keep],
            priorities=[self.priorities[i] for i in keep],
            languages=[self.languages[i] for i in keep],
        )


def _to_text(name: str, content: str) -> str:
    """How a ticket is presented to the model.

    Title and body are joined rather than used separately: a real service desk
    has both, and the title carries most of the signal.
    """
    return f"{name}\n{content}"


def build_dataset(
    count: int,
    *,
    seed: int = 42,
    languages: list[Language] | None = None,
) -> Dataset:
    """Generate ``count`` labelled tickets."""
    tickets = TicketGenerator(seed=seed, languages=languages).generate(count)
    return Dataset(
        texts=[_to_text(ticket.name, ticket.content) for ticket in tickets],
        categories=[ticket.category for ticket in tickets],
        priorities=[int(ticket.priority) for ticket in tickets],
        languages=[ticket.language for ticket in tickets],
    )


def deduplicate_against(test: Dataset, train: Dataset) -> Dataset:
    """Drop the rows of ``test`` whose text also occurs in ``train``.

    Without this the score is inflated by memorisation: the templates saturate,
    so roughly a quarter of any test batch is text the model has already seen.
    """
    seen = set(train.texts)
    keep = [index for index, text in enumerate(test.texts) if text not in seen]
    return Dataset(
        texts=[test.texts[i] for i in keep],
        categories=[test.categories[i] for i in keep],
        priorities=[test.priorities[i] for i in keep],
        languages=[test.languages[i] for i in keep],
    )


def train_test_split(
    count: int,
    *,
    seed: int = 42,
    test_fraction: float = 0.25,
    deduplicate: bool = True,
) -> tuple[Dataset, Dataset]:
    """Build a train and a test set.

    The halves come from different generator seeds, and — because the template
    space saturates and different seeds still collide — the test half is then
    deduplicated against the training half. Pass ``deduplicate=False`` to see
    the inflated numbers for yourself.

    The test set therefore ends up smaller than ``count * test_fraction``.
    """
    if not 0 < test_fraction < 1:
        raise ValueError("test_fraction must be between 0 and 1")

    test_size = max(1, int(count * test_fraction))
    train_size = count - test_size
    if train_size < 1:
        raise ValueError("count is too small to split")

    train = build_dataset(train_size, seed=seed)
    test = build_dataset(test_size, seed=seed + 10_000)

    if deduplicate:
        test = deduplicate_against(test, train)
        if not len(test):
            raise ValueError(
                "every test ticket also appeared in training; raise count or "
                "add catalogue entries to glpi-testkit"
            )
    return train, test


def dataset_summary(dataset: Dataset) -> dict[str, Any]:
    """Label and language distribution, for the model card."""

    def counts(values: list[Any]) -> dict[str, int]:
        result: dict[str, int] = {}
        for value in values:
            key = str(value)
            result[key] = result.get(key, 0) + 1
        return dict(sorted(result.items()))

    unique = len(set(dataset.texts))
    return {
        "size": len(dataset),
        "unique_texts": unique,
        "text_diversity": round(unique / len(dataset), 4) if len(dataset) else 0.0,
        "languages": counts(dataset.languages),
        "categories": counts(dataset.categories),
        "priorities": counts(dataset.priorities),
    }
